@echo off
echo Translating English text to Persian and fixing RTL issues...

echo Updating index.html...
powershell -Command "(Get-Content 'templates/index.html') -replace 'lang=\"en-US\"', 'lang=\"fa-IR\"' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'MediClinic', 'نگهداشت' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'A Multipurpose Health and Medical Theme', 'سامانه مدیریت تجهیزات پزشکی' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Home', 'خانه' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Main Home', 'صفحه اصلی' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'About Us', 'درباره ما' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Our Services', 'خدمات ما' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Contact Us', 'تماس با ما' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Doctors', 'پزشکان' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Our Doctors', 'پزشکان ما' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Blog', 'بلاگ' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Search', 'جستجو' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Related Posts', 'پست های مرتبط' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Contact form', 'فرم تماس' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Team List', 'لیست تیم' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Typography', 'تایپوگرافی' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Headings', 'سرصفحه ها' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Columns', 'ستون ها' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Section Title', 'عنوان بخش' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Blockquote', 'نقل قول' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Custom Fonts', 'فونت های سفارشی' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Dropcaps', 'حروف بزرگ' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Highlights', 'نکات برجسته' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Icon List Item', 'آیتم لیست آیکون' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Icon Box', 'جعبه آیکون' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Right Sidebar', 'نوار کناری راست' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Left Sidebar', 'نوار کناری چپ' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Without Sidebar', 'بدون نوار کناری' | Set-Content 'templates/index.html'"
powershell -Command "(Get-Content 'templates/index.html') -replace 'Doctor Showcase', 'نمایش پزشک' | Set-Content 'templates/index.html'"

echo Updating blog.html...
powershell -Command "(Get-Content 'templates/blog.html') -replace 'lang=\"en-US\"', 'lang=\"fa-IR\"' | Set-Content 'templates/blog.html'"
powershell -Command "(Get-Content 'templates/blog.html') -replace 'MediClinic', 'نگهداشت' | Set-Content 'templates/blog.html'"
powershell -Command "(Get-Content 'templates/blog.html') -replace 'Home', 'خانه' | Set-Content 'templates/blog.html'"
powershell -Command "(Get-Content 'templates/blog.html') -replace 'About Us', 'درباره ما' | Set-Content 'templates/blog.html'"
powershell -Command "(Get-Content 'templates/blog.html') -replace 'Our Services', 'خدمات ما' | Set-Content 'templates/blog.html'"
powershell -Command "(Get-Content 'templates/blog.html') -replace 'Contact Us', 'تماس با ما' | Set-Content 'templates/blog.html'"
powershell -Command "(Get-Content 'templates/blog.html') -replace 'Doctors', 'پزشکان' | Set-Content 'templates/blog.html'"
powershell -Command "(Get-Content 'templates/blog.html') -replace 'Blog', 'بلاگ' | Set-Content 'templates/blog.html'"
powershell -Command "(Get-Content 'templates/blog.html') -replace 'Search', 'جستجو' | Set-Content 'templates/blog.html'"

echo Updating blog_list.html...
powershell -Command "(Get-Content 'templates/blog_list.html') -replace 'lang=\"en-US\"', 'lang=\"fa-IR\"' | Set-Content 'templates/blog_list.html'"
powershell -Command "(Get-Content 'templates/blog_list.html') -replace 'MediClinic', 'نگهداشت' | Set-Content 'templates/blog_list.html'"
powershell -Command "(Get-Content 'templates/blog_list.html') -replace 'Home', 'خانه' | Set-Content 'templates/blog_list.html'"
powershell -Command "(Get-Content 'templates/blog_list.html') -replace 'About Us', 'درباره ما' | Set-Content 'templates/blog_list.html'"
powershell -Command "(Get-Content 'templates/blog_list.html') -replace 'Our Services', 'خدمات ما' | Set-Content 'templates/blog_list.html'"
powershell -Command "(Get-Content 'templates/blog_list.html') -replace 'Contact Us', 'تماس با ما' | Set-Content 'templates/blog_list.html'"
powershell -Command "(Get-Content 'templates/blog_list.html') -replace 'Doctors', 'پزشکان' | Set-Content 'templates/blog_list.html'"
powershell -Command "(Get-Content 'templates/blog_list.html') -replace 'Blog', 'بلاگ' | Set-Content 'templates/blog_list.html'"
powershell -Command "(Get-Content 'templates/blog_list.html') -replace 'Search', 'جستجو' | Set-Content 'templates/blog_list.html'"

echo Updating device_list.html...
powershell -Command "(Get-Content 'templates/device_list.html') -replace 'lang=\"en-US\"', 'lang=\"fa-IR\"' | Set-Content 'templates/device_list.html'"
powershell -Command "(Get-Content 'templates/device_list.html') -replace 'MediClinic', 'نگهداشت' | Set-Content 'templates/device_list.html'"
powershell -Command "(Get-Content 'templates/device_list.html') -replace 'Home', 'خانه' | Set-Content 'templates/device_list.html'"
powershell -Command "(Get-Content 'templates/device_list.html') -replace 'About Us', 'درباره ما' | Set-Content 'templates/device_list.html'"
powershell -Command "(Get-Content 'templates/device_list.html') -replace 'Our Services', 'خدمات ما' | Set-Content 'templates/device_list.html'"
powershell -Command "(Get-Content 'templates/device_list.html') -replace 'Contact Us', 'تماس با ما' | Set-Content 'templates/device_list.html'"
powershell -Command "(Get-Content 'templates/device_list.html') -replace 'Doctors', 'پزشکان' | Set-Content 'templates/device_list.html'"
powershell -Command "(Get-Content 'templates/device_list.html') -replace 'Blog', 'بلاگ' | Set-Content 'templates/device_list.html'"
powershell -Command "(Get-Content 'templates/device_list.html') -replace 'Search', 'جستجو' | Set-Content 'templates/device_list.html'"

echo Updating device_details.html...
powershell -Command "(Get-Content 'templates/device_details.html') -replace 'lang=\"en-US\"', 'lang=\"fa-IR\"' | Set-Content 'templates/device_details.html'"
powershell -Command "(Get-Content 'templates/device_details.html') -replace 'MediClinic', 'نگهداشت' | Set-Content 'templates/device_details.html'"
powershell -Command "(Get-Content 'templates/device_details.html') -replace 'Home', 'خانه' | Set-Content 'templates/device_details.html'"
powershell -Command "(Get-Content 'templates/device_details.html') -replace 'About Us', 'درباره ما' | Set-Content 'templates/device_details.html'"
powershell -Command "(Get-Content 'templates/device_details.html') -replace 'Our Services', 'خدمات ما' | Set-Content 'templates/device_details.html'"
powershell -Command "(Get-Content 'templates/device_details.html') -replace 'Contact Us', 'تماس با ما' | Set-Content 'templates/device_details.html'"
powershell -Command "(Get-Content 'templates/device_details.html') -replace 'Doctors', 'پزشکان' | Set-Content 'templates/device_details.html'"
powershell -Command "(Get-Content 'templates/device_details.html') -replace 'Blog', 'بلاگ' | Set-Content 'templates/device_details.html'"
powershell -Command "(Get-Content 'templates/device_details.html') -replace 'Search', 'جستجو' | Set-Content 'templates/device_details.html'"

echo All translations completed! Persian text and RTL fixes applied.
pause
